version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:438465134214:task-definition/zin-TD:1"
        LoadBalancerInfo:
          ContainerName: simp
          ContainerPort: 3000
